services:
  postgres:
    image: postgres:16-alpine
    container_name: express_app_postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: express_app
      POSTGRES_PASSWORD: express_app
      POSTGRES_DB: express_app
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
